# Generated by Django 6.0.6 on 2026-06-04 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authencation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('unknown', 'Belgilanmagan'), ('teacher', "O'qituvchi"), ('pupil', "O'quvchi"), ('admin', 'Admin'), ('manager', 'Menejer'), ('cashier', 'Kassir'), ('registrator', 'Registrator')], default='unknown', max_length=20),
        ),
    ]
