# Generated by Django 6.0.6 on 2026-06-06 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authencation', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
