# Generated by Django 6.0.6 on 2026-06-06 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('education', '0002_alter_time_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='subjects',
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='education.course'),
        ),
    ]
