# Generated by Django 6.0.6 on 2026-06-06 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='time',
            unique_together={('days', 'time_start', 'time_end')},
        ),
    ]
